MONGODB_HOST: mongodb.somayya.fun
REDIS_HOST: redis.somayya.fun
CATALOGUE_HOST: catalogue.somayya.fun
CART_HOST: cart.somayya.fun
MYSQL_HOST: mysql.somayya.fun
USER_HOST: user.somayya.fun
RABBITMQ_HOST: rabbitmq.somayya.fun
SHIPPING_HOST: shipping.somayya.fun
PAYMENT_HOST: payment.somayya.fun