MONGODB_HOST: mongodb-{{ env }}.somayya.fun
REDIS_HOST: redis-{{ env }}.somayya.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.somayya.fun
CART_HOST: cart.backend-alb-{{ env }}.somayya.fun
MYSQL_HOST: mysql-{{ env }}.somayya.fun
USER_HOST: user.backend-alb-{{ env }}.somayya.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.somayya.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.somayya.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.somayya.fun