MONGODB_HOST: mongodb-{{ env }}.somayya.fun
REDIS_HOST: redis-{{ env }}.somayya.fun
CATALOGUE_HOST: catalogue-{{ env }}.somayya.fun
CART_HOST: cart-{{ env }}.somayya.fun
MYSQL_HOST: mysql-{{ env }}.somayya.fun
USER_HOST: user-{{ env }}.somayya.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.somayya.fun
SHIPPING_HOST: shipping-{{ env }}.somayya.fun
PAYMENT_HOST: payment-{{ env }}.somayya.fun